
serial:
	mpic++ -std=c++11 serial.cpp -o serial -I/usr/local/include/c++/4.9.0/ -I/usr/local/include/c++/4.9.0/x86_64-apple-darwin13.1.0

helloworld:
	mpic++ helloworld.cpp -o hello

clean: 
	rm -rf *.o
	rm serial 
	rm hello