
INCLUDE_PATH=..

all: serial_1 serial_2 serial_3 serial_4 serial_5 serial_6

serial_1:
	gcc -o ./build/serial_1 ./1.c -lm -I$(INCLUDE_PATH) -std=c99 -O0

serial_2:
	gcc -o ./build/serial_2 ./2.c -lm -I$(INCLUDE_PATH) -std=c99 -O0

serial_3:
	gcc -o ./build/serial_3 ./3.c -lm -I$(INCLUDE_PATH) -std=c99 -O0

serial_4:
	gcc -o ./build/serial_4 ./4.c -lm -I$(INCLUDE_PATH) -std=c99 -O0

serial_5:
	gcc -o ./build/serial_5 ./5.c -lm -I$(INCLUDE_PATH) -std=c99 -O0

serial_6:
	gcc -o ./build/serial_6 ./6.c -lm -I$(INCLUDE_PATH) -std=c99 -O0
clean:
	rm -rf ./build/*
